title: Jianghao Cao's Homepage
page-top-title: Jianghao Cao
top-section-bg-text: Mathematics and Applied Mathematics
home-subtitle: Jianghao Cao&ensp;|&ensp;曹江昊
copyright-text: '&copy; Jianghao Cao 2024-2025. All Rights Reserved.'
